components/achievementcard.tsx, components/bundles/bundleCard.tsx, components/bundles/bundleCell.tsx, components/infocard.tsx, components/sidebarlayout.tsx, package.json, pages/bundles.tsx, pages/farmer.tsx, pages/fishing.tsx, research/processors/achievements.py, research/processors/data/achievements.json, research/raw_data/Achievements.json, types/bundles.ts, types/general.ts, types/index.ts, types/items.ts, utils/index.ts, utils/parsers/general.ts, utils/parsers/money.ts, utils/parsers/name.ts, yarn.lock
Created this branch to test out some of the file parsing which appears to work as intended. Lots more work to do like utilizing the parsed data to set local storage.
=> Save File Parser demo + new farmer page and achievements

research/processors/monster_processor.py
I don't even play this game + It's 2:20AM i have no idea how i conjured this up
=> fix(processors): properly scrape monsters

.gitignore, research/processors/monster_processor.py
Sample Output:
```json
{
"Slime": {
"Monster Type": [
"Slime (any color,excludes Big Slimes and Slimes in Slime Hutch)",
"/mediawiki/images/thumb/7/7b/Green_Slime.png/24px-Green_Slime.png"
],
"Quantity": "1000",
"Reward": [
"Slime Charmer Ring",
"/mediawiki/images/thumb/5/51/Slime_Charmer_Ring.png/24px-Slime_Charmer_Ring.png"
],
"Reward Description": "Prevents damage from slimes."
},
"Void Spirits:": {
"Monster Type": [
[
"Shadow Shaman",
"/mediawiki/images/thumb/1/11/Shadow_Shaman.png/16px-Shadow_Shaman.png"
],
[
"Shadow Shaman (dangerous)",
"/mediawiki/images/thumb/d/d9/Shadow_Shaman_Dangerous.png/16px-Shadow_Shaman_Dangerous.png"
],
[
"Shadow Brute",
"/mediawiki/images/thumb/e/e0/Shadow_Brute.png/16px-Shadow_Brute.png"
],
[
"Shadow Brute (dangerous)", …
```
=> fix: scraping monsters does not properly scrape rewards

components/inputs/draganddrop.tsx, components/sidebarlayout.tsx, pages/index.tsx, pages/perfection.tsx
also: imported useref, made file picker (semi)functional, moved button classes to navigation const for easier mobile styling, added side padding on mobile, resized heart emoji to fit text
=> feat(pr): use file picker on index page

package.json, pages/_app.tsx, yarn.lock
=> Add Fathom Analytics

components/sidebarlayout.tsx, pages/artifacts.tsx, pages/index.tsx, utils/file.ts, utils/parsers/museum.ts
- Uploading a save file now marks artifacts/minerals
- Museum parser now includes artifact/mineral donated count
- Museum achievements are now correctly toggled based on total values
- File upload is now abstracted to a function to be used in sidebar/index page
=> Museum page/parser improvements

components/cards/villagercard.tsx, components/sidebarlayout.tsx, components/slideovers/itemDisplay.tsx, components/slideovers/villagerslideover.tsx, pages/social.tsx, research/processors/data/villagers.json, research/processors/villagers.py, research/raw_data/NPCDispositions.json, research/raw_data/NPCGiftTastes.json, utils/file.ts, utils/parsers/social.ts
=> 6 social tab

components/sidebarlayout.tsx
Issue #29: Update Mobile Sidebar
- Also added discord & github icons to the mobile navbar to match the desktop UI
=> Updated Mobile Sidebar (Resolves #29)

components/popup.tsx
Im so sorry for *another* PR on the same mobile-navbar issue lmao it was late and i accidentally deleted the z-index that fixed the mobile modal window
but uh it should be fixed now, video below of the result, hoping this one *actually* works
https://user-images.githubusercontent.com/29960599/186679698-0022385e-99bb-4c0a-9982-497326ab7bdf.mp4
=> fix(sidebar-mobile): Fixed z-index of modal popup on mobile navbar

components/cards/achievementcard.tsx, components/cards/booleancard.tsx, components/cards/expandablecard.tsx, components/cards/monstercard.tsx, components/cards/recipecard.tsx, components/filterbtn.tsx, components/popup.tsx, pages/_app.tsx, pages/api/getCategoryInfo.ts, pages/api/kv.ts, pages/api/oauth/callback.ts, pages/api/oauth/index.ts, pages/artifacts.tsx, pages/cooking.tsx, pages/crafting.tsx, pages/farmer.tsx, pages/fishing.tsx, research/processors/data/fish.json, research/processors/fish_splitter.py, types/general.ts, types/index.ts, types/sprites.ts, utils/file.ts, utils/parsers/museum.ts, utils/useCategory.ts
Turned the informational badges into clickable filters
Used Alistair's project component to design these expandable cards for stardrops and museum items (thanks @alii)
=> 21 filtering capability

components/desktopnav.tsx, components/mobilenav.tsx, components/modals/credits.tsx, components/sidebarlayout.tsx
Issue #50 
Changed all instances of https://github.com/stardewapp to https://github.com/communitycenter/stardew.app.
credits.tsx had a link to https://github.com/stardewapp/stardew.app, which *was* properly redirecting, but I updated it anyway. Happy to change it back if needed.
=> Fixed issue 50

src/lib/file.ts, src/lib/parsers/bundles.ts, src/lib/parsers/index.ts, src/lib/utils.ts, src/types/bundles.ts
Added a bundle parser to get all of the bundle info from the save file and output it for use in the UI.
=> Added a bundle parser

src/data/objects.json
I was working on updating the python script to actually output the updated names and description, but I don't have a copy of the 1.6 alpha to test it. I'll toss that in a separate PR.
=> Updated dried fruit and mushroom to have correct name (and description for fruit)

README.md
Forgot to update the readme lmao
=> Update readme for bundles tracker

README.md
Commented the item.ts file and for some reason readme decided to change sorry.
=> Commenting item.ts file

src/data/fish.json
I reran the fish.py script and it generated a fairly large diff. I assume this is because the wiki has been updated significantly in the last several weeks.
=> Reran fish.py to get updated info

scripts/cooking.py, scripts/helpers/utils.py, src/data/cooking.json
It wasn't calculating the end of year recipes correctly since the air date key is 1-indexed.
=> Apparently the cooking air date math was off

src/pages/skills.tsx
This PR closes issue #118, placing the [Well-Read](https://stardewvalleywiki.com/Books) achievement in the Skills & Mastery section.
=> Add "Well-Read" achievement tracking - Closes #118

src/pages/perfection.tsx
This PR tracks the achievement "Protector Of The Valley", related to the completion of the Monster Slayer goals.
=> Add missing achievement tracker

src/pages/farmer.tsx
This PR:
- Changes the title of the "Money Earned" and "Player Name" infoCards;
- Changes the position of some infoCards.
(Read the commits' descriptions for details).
=> Slight code refactor in "Farmer" page

src/pages/bundles.tsx, src/pages/cooking.tsx, src/pages/crafting.tsx, src/pages/fishing.tsx, src/pages/museum.tsx, src/pages/relationships.tsx
This PR:
- Changes all instances of remaining items to "number left", since not only that seems to be the standard choice, but it also conveys the meaning better.
=> Make verbiage of remaining items consistent

src/pages/perfection.tsx
This PR makes a bunch of changes to the Perfection page in order to allow the mentioned feature; the main point is to make the memos consider the highest values between the farmers in order to choose which one to display.
=> Resolve [STA-172] - Combined perfection values from each player

src/lib/file.ts, src/lib/parsers/animals.ts, src/lib/parsers/index.ts
This PR allows the processed player to have farm animals, pets and horse information.
=> Resolve [STA-89] - Animal relationships parser

src/components/top-bar.tsx, src/pages/relationships.tsx
Also cleaned up some unused code in the latter commit
=> Feature: Show 'Roommate' instead of 'Spouse' if current spouse is 'Krobus'
